### ISSUE TITLE
Última ronda

### ISSUE THREAD

**Issue by rgonzalezt** [Facundo-Vattone/Tp_monopoly#5]
Lo que nos pide el enunciado para esta función es:

> modelar la función últimaRonda, que dado un participante retorna una acción equivalente a todas sus acciones.

Entonces, lo que tiene que hacer `ultimaRonda` no es devolver un `Jugador` sino que toma a un `Jugador` y devuelve una `Accion`. Podemos pensarlo como que tenemos que devolver una "gran acción" que es la concatenación de todas las acciones de la persona.

Luego sí vas a tener que hacer una función para que la persona juegue la última ronda. Es decir, que aplique esa "gran acción" a la persona.

Por último:

- Estás repitiendo lógica a la hora de saber el _dinero al final_ de un jugador. Delegá esa lógica en otra función.

- Tené en cuenta que en `juegoFinal` no hay que devolver una lista, sino a un `Jugador`. Si hay empate, no sabemos qué pasa por lo que: le preguntás al docente o asumís que pasa algo sin cambiar el tipo de la función. En este caso, te recomiendo que no pienses en el empate. **Cuidado esto a la hora del parcial**. Más allá de eso, la lógica de esta función está bien.

**Re-hacer este punto teniendo en cuenta lo anterior dicho.**

**Comment by rgonzalezt** [comment]
¡Muy bien! Un último último detallito, en la función `ganaElPrimero`, cuando comparás el dinero de los jugadores, deberías fijarte por el dinero que les queda _después_ de la última ronda.

**Comment by Facundo-Vattone** [comment]
Profe no entendí bien la corrección. A la función mencionada la llegan como parámetros: carolina y manuel que a esos mismo previamente se les aplica la función aplicarUltimaRonda, y así con eso se los compara ya modificados.

**Comment by rgonzalezt** [comment]
Sí, perdón, me confundí yo. Igualmente el `Jugador` que devuelve `juegoFinal` debería el mismo después de que juegue la última ronda. Es decir:

```haskell
juegoFinal :: Jugador -> Jugador -> Jugador
juegoFinal unJugador otroJugador
 | ganaElPrimero (aplicarUltimaRonda unJugador) ( aplicarUltimaRonda otroJugador) = aplicarUltimaRonda unJugador 
 | otherwise                                                                      = aplicarUltimaRonda otroJugador
```

No hace falta que lo corrijas pero sí tenelo en cuenta para futuros ejercicios. 🙌

**Comment by Facundo-Vattone** [comment]
perfecto. Muchas gracias profe!
